baseurl = "https://vishwasvr.github.io"
title = "Vishwas Vankalapati"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "It's All About DATA!"
  slogan = "Data Engineering - The how's and why's"
  SEOTitle = "Vishwas Vankalapati Blog"
  keyword = "Vishwas, Vankalapati, Data, Engineer, Visualization, Analytics, BI, Cloud, AWS, Tableau, Cognos, Power BI, Python, Spark, Glue, RDS, SQL"

  # Sidebar settings
  sidebar_about_description = "Husband, Travler, and, oh yeah, Data Engineer"
  sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false


  [[params.addtional_menus]]
  title =  "Programming"
  href =  "/categories/prgramming/"
  [[params.addtional_menus]]
  title =  "Modelling"
  href =  "/categories/modelling/"
  [[params.addtional_menus]]
  title =  "Storage"
  href =  "/categories/storage/"
  [[params.addtional_menus]]
  title =  "Analytics"
  href =  "/categories/analytics/"
  [[params.addtional_menus]]
  title =  "Visualization"
  href =  "/categories/visualization/"
  [[params.addtional_menus]]
  title =  "Learn"
  href =  "/categories/learn/"
  [[params.addtional_menus]]
  title =  "Resources"
  href =  "/categories/resources/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "vishwasvr@gmail.com"
  linkedin       = "https://www.linkedin.com/in/vishwas-vankalapati/"
  github         = "https://github.com/vishwasvr"
  medium         = "https://medium.com/@vishwasvr"
  stackoverflow  = "https://stackoverflow.com/users/10349122/vishwasvr"
